/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IIncentive } from "../IIncentive";

export class IIncentive__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IIncentive {
    return new Contract(address, _abi, signerOrProvider) as IIncentive;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "incentivize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
