/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  BigNumberish,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { MockTWAPOracle } from "../MockTWAPOracle";

export class MockTWAPOracle__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _pool: string,
    _uADtoken0: string,
    _curve3CRVtoken1: string,
    _price0Average: BigNumberish,
    _price1Average: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MockTWAPOracle> {
    return super.deploy(
      _pool,
      _uADtoken0,
      _curve3CRVtoken1,
      _price0Average,
      _price1Average,
      overrides || {}
    ) as Promise<MockTWAPOracle>;
  }
  getDeployTransaction(
    _pool: string,
    _uADtoken0: string,
    _curve3CRVtoken1: string,
    _price0Average: BigNumberish,
    _price1Average: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      _pool,
      _uADtoken0,
      _curve3CRVtoken1,
      _price0Average,
      _price1Average,
      overrides || {}
    );
  }
  attach(address: string): MockTWAPOracle {
    return super.attach(address) as MockTWAPOracle;
  }
  connect(signer: Signer): MockTWAPOracle__factory {
    return super.connect(signer) as MockTWAPOracle__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockTWAPOracle {
    return new Contract(address, _abi, signerOrProvider) as MockTWAPOracle;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
      {
        internalType: "address",
        name: "_uADtoken0",
        type: "address",
      },
      {
        internalType: "address",
        name: "_curve3CRVtoken1",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_price0Average",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_price1Average",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "consult",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "price0Average",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "price1Average",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "priceCumulativeLast",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pricesBlockTimestampLast",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "update",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60e060405234801561001057600080fd5b506040516103e13803806103e183398101604081905261002f9161007e565b6001600160601b0319606095861b811660805293851b841660a0529190931b90911660c0526000919091556001556100d3565b80516001600160a01b038116811461007957600080fd5b919050565b600080600080600060a08688031215610095578081fd5b61009e86610062565b94506100ac60208701610062565b93506100ba60408701610062565b6060870151608090970151959894975095949392505050565b60805160601c60a05160601c60c05160601c6102c96101186000396000818161016901526101d201526000818160c9015261018f0152600061010801526102c96000f3fe608060405234801561001057600080fd5b50600436106100a35760003560e01c80635e6aaf2c11610076578063a2e620451161005b578063a2e6204514610159578063a6bb45391461015b578063d21220a714610164576100a3565b80635e6aaf2c1461013d5780637536a29114610146576100a3565b80630301b16e146100a85780630dfe1681146100c457806316f0115b14610103578063283583c61461012a575b600080fd5b6100b160025481565b6040519081526020015b60405180910390f35b6100eb7f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b0390911681526020016100bb565b6100eb7f000000000000000000000000000000000000000000000000000000000000000081565b6100b1610138366004610276565b61018b565b6100b160015481565b6100b16101543660046102a4565b61025f565b005b6100b160005481565b6100eb7f000000000000000000000000000000000000000000000000000000000000000081565b60007f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316826001600160a01b031614156101d0575060005461025a565b7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316826001600160a01b0316146102555760405162461bcd60e51b815260206004820152601960248201527f545741504f7261636c653a20494e56414c49445f544f4b454e00000000000000604482015260640160405180910390fd5b506001545b919050565b6003816002811061026f57600080fd5b0154905081565b600060208284031215610287578081fd5b81356001600160a01b038116811461029d578182fd5b9392505050565b6000602082840312156102b5578081fd5b503591905056fea164736f6c6343000803000a";
