/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IDollarMintingCalculator } from "../IDollarMintingCalculator";

export class IDollarMintingCalculator__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDollarMintingCalculator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IDollarMintingCalculator;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getDollarsToMint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
