/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IUbiquityFormulas } from "../IUbiquityFormulas";

export class IUbiquityFormulas__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUbiquityFormulas {
    return new Contract(address, _abi, signerOrProvider) as IUbiquityFormulas;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_totalULP",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_totalUBOND",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_targetPrice",
        type: "uint256",
      },
    ],
    name: "bondPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "_priceUBOND",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_shares",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_currentShareValue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_targetPrice",
        type: "uint256",
      },
    ],
    name: "bonding",
    outputs: [
      {
        internalType: "uint256",
        name: "_uBOND",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_uLP",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_weeks",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_multiplier",
        type: "uint256",
      },
    ],
    name: "durationMultiply",
    outputs: [
      {
        internalType: "uint256",
        name: "_shares",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_uBOND",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_currentShareValue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_targetPrice",
        type: "uint256",
      },
    ],
    name: "redeemBonds",
    outputs: [
      {
        internalType: "uint256",
        name: "_uLP",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_multiplier",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "ugovMultiply",
    outputs: [
      {
        internalType: "uint256",
        name: "_newMultiplier",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];
