// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol. SEE BELOW FOR SOURCE. !!
pragma solidity ^0.8.3;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";

import "../UbiquityChef.sol";

interface IUbiquityChef {
    struct StakingTokenInfo {
        uint256 amount; // How many LP tokens the user has provided.
        uint256 rewardDebt; // Reward debt. See explanation below.
    }

    struct PoolInfo {
        uint256 lastRewardBlock; // Last block number that Governance Token distribution occurs.
        uint256 accGovernancePerShare; // Accumulated Governance Token per share, times 1e12. See below.
    }

    event Deposit(address indexed user, uint256 amount, uint256 stakingShareID);
    event Withdraw(
        address indexed user,
        uint256 amount,
        uint256 stakingShareID
    );

    function deposit(
        address sender,
        uint256 amount,
        uint256 stakingShareID
    ) external;

    // Withdraw LP tokens from MasterChef.
    function withdraw(
        address sender,
        uint256 amount,
        uint256 stakingShareID
    ) external;

    // Info about a staking share
    function getStakingTokenInfo(
        uint256 _id
    ) external view returns (uint256[2] memory);

    // Total amount of shares
    function totalShares() external view returns (uint256);

    // View function to see pending Governance Tokens on frontend.
    function pendingGovernance(address _user) external view returns (uint256);
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
