#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn format
# git diff --name-only | npx cspell --file-list stdin
# exec git diff --cached --name-only | npx cspell --no-summary --no-progress --no-must-find-files --file-list stdin
